// <auto-generated />
using System;
using E_commerceAPI.DAL.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_commerceAPI.DAL.Migrations
{
    [DbContext(typeof(E_commerceContext))]
    [Migration("20240509041228_productSeeding")]
    partial class productSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_commerceAPI.DAL.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dell"
                        },
                        new
                        {
                            Id = 3,
                            Name = "HP"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Lenovo"
                        },
                        new
                        {
                            Id = 5,
                            Name = "ASUS"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Acer"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Microsoft"
                        },
                        new
                        {
                            Id = 8,
                            Name = "MSI"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Razer"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Samsung"
                        });
                });

            modelBuilder.Entity("E_commerceAPI.DAL.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "The Apple MacBook Air is a lightweight and portable laptop with excellent battery life.",
                            Discount = 50m,
                            Model = "MacBook Air",
                            Name = "Apple MacBook Air",
                            Price = 40000m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "The Apple MacBook Pro is a high-performance laptop loved by professionals.",
                            Discount = 20m,
                            Model = "MacBook Pro",
                            Name = "Apple MacBook Pro",
                            Price = 80000m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "The Dell XPS 13 is a sleek and powerful laptop with a stunning display.",
                            Discount = 0m,
                            Model = "XPS 13",
                            Name = "Dell XPS 13",
                            Price = 40000m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "The Dell Inspiron 15 is a versatile laptop suitable for everyday use.",
                            Discount = 13m,
                            Model = "Inspiron 15",
                            Name = "Dell Inspiron 15",
                            Price = 35000m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "The HP Spectre x360 is a stylish 2-in-1 laptop with powerful performance.",
                            Discount = 15m,
                            Model = "Spectre x360",
                            Name = "HP Spectre x360",
                            Price = 25000m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Description = "The HP Pavilion 14 is a budget-friendly laptop with decent specifications.",
                            Discount = 60m,
                            Model = "Pavilion 14",
                            Name = "HP Pavilion 14",
                            Price = 15000m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Description = "The Apple MacBook Air is a lightweight and portable laptop with excellent battery life.",
                            Discount = 10m,
                            Model = "MacBook Air",
                            Name = "Apple MacBook Air",
                            Price = 28000m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Description = "The Apple MacBook Pro is a high-performance laptop loved by professionals.",
                            Discount = 12m,
                            Model = "MacBook Pro",
                            Name = "Apple MacBook Pro",
                            Price = 30000m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            Description = "The Apple iMac is a sleek and powerful all-in-one desktop computer.",
                            Discount = 0m,
                            Model = "iMac",
                            Name = "Apple iMac",
                            Price = 16000m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Description = "The Dell XPS 13 is a sleek and powerful laptop with a stunning display.",
                            Discount = 90m,
                            Model = "XPS 13",
                            Name = "Dell XPS 13",
                            Price = 14000m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Description = "The Dell Inspiron 15 is a versatile laptop suitable for everyday use.",
                            Discount = 18m,
                            Model = "Inspiron 15",
                            Name = "Dell Inspiron 15",
                            Price = 30000m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Description = "The Dell G5 Gaming Desktop is a powerful gaming machine with immersive graphics.",
                            Discount = 20m,
                            Model = "G5 Gaming Desktop",
                            Name = "Dell G5 Gaming Desktop",
                            Price = 38000m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            Description = "The HP Spectre x360 is a stylish 2-in-1 laptop with powerful performance.",
                            Discount = 19m,
                            Model = "Spectre x360",
                            Name = "HP Spectre x360",
                            Price = 26000m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            Description = "The HP Pavilion 14 is a budget-friendly laptop with decent specifications.",
                            Discount = 0m,
                            Model = "Pavilion 14",
                            Name = "HP Pavilion 14",
                            Price = 6000m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 3,
                            Description = "The HP EliteBook 840 is a business laptop with top-notch security features.",
                            Discount = 80m,
                            Model = "EliteBook 840",
                            Name = "HP EliteBook 840",
                            Price = 50000m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            Description = "The Apple MacBook Air is a lightweight and portable laptop with excellent battery life.",
                            Discount = 15m,
                            Model = "MacBook Air",
                            Name = "Apple MacBook Air",
                            Price = 18000m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Description = "The Dell XPS 13 is a sleek and powerful laptop with a stunning display.",
                            Discount = 5m,
                            Model = "XPS 13",
                            Name = "Dell XPS 13",
                            Price = 13000m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            Description = "The HP Spectre x360 is a stylish 2-in-1 laptop with powerful performance.",
                            Discount = 10m,
                            Model = "Spectre x360",
                            Name = "HP Spectre x360",
                            Price = 12000m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 4,
                            Description = "The Lenovo ThinkCentre M720 is a compact and reliable desktop computer for business use.",
                            Discount = 6m,
                            Model = "ThinkCentre M720",
                            Name = "Lenovo ThinkCentre M720",
                            Price = 15000m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            Description = "The ASUS ROG Strix G15 is a powerful gaming desktop with RGB lighting and high-performance components.",
                            Discount = 60m,
                            Model = "ROG Strix G15",
                            Name = "ASUS ROG Strix G15",
                            Price = 80000m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 6,
                            Description = "The Acer Aspire TC is a budget-friendly desktop computer with decent performance.",
                            Discount = 15m,
                            Model = "Aspire TC",
                            Name = "Acer Aspire TC",
                            Price = 18000m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 2,
                            Description = "The Dell Inspiron 27 is an all-in-one desktop computer with a large display and powerful performance.",
                            Discount = 10m,
                            Model = "Inspiron 27",
                            Name = "Dell Inspiron 27",
                            Price = 22000m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 5,
                            Description = "The ASUS ZenBook Pro is a premium laptop with a stunning 4K display and high-performance components.",
                            Discount = 15m,
                            Model = "ZenBook Pro",
                            Name = "ASUS ZenBook Pro",
                            Price = 28000m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            Description = "The HP Pavilion Gaming Desktop is a gaming powerhouse with advanced graphics and smooth gameplay.",
                            Discount = 80m,
                            Model = "Pavilion Gaming Desktop",
                            Name = "HP Pavilion Gaming Desktop",
                            Price = 15000m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 4,
                            Description = "The Lenovo Legion Y540 is a gaming laptop with powerful hardware and immersive gaming experience.",
                            Discount = 12m,
                            Model = "Legion Y540",
                            Name = "Lenovo Legion Y540",
                            Price = 20000m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 1,
                            Description = "The Apple iMac is a sleek all-in-one desktop computer with a stunning Retina display and powerful performance.",
                            Discount = 20m,
                            Model = "iMac",
                            Name = "Apple iMac",
                            Price = 24000m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 2,
                            Description = "The Dell G5 is a gaming laptop with high-performance hardware and immersive gaming features.",
                            Discount = 10m,
                            Model = "G5 Gaming Laptop",
                            Name = "Dell G5 Gaming Laptop",
                            Price = 18000m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 3,
                            Description = "The HP Envy 15 is a premium laptop with a sleek design and powerful performance for multimedia and productivity tasks.",
                            Discount = 15m,
                            Model = "Envy 15",
                            Name = "HP Envy 15",
                            Price = 16000m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 4,
                            Description = "The Lenovo IdeaCentre 5 is a compact and versatile desktop computer suitable for home and office use.",
                            Discount = 50m,
                            Model = "IdeaCentre 5",
                            Name = "Lenovo IdeaCentre 5",
                            Price = 8990m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 5,
                            Description = "The ASUS VivoBook S15 is a stylish and lightweight laptop with a vibrant display and long battery life.",
                            Discount = 0m,
                            Model = "VivoBook S15",
                            Name = "ASUS VivoBook S15",
                            Price = 9990m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 10,
                            Description = "The Samsung Galaxy Book Pro is a thin and lightweight laptop with a stunning AMOLED display and powerful performance.",
                            Discount = 10m,
                            Model = "Galaxy Book Pro",
                            Name = "Samsung Galaxy Book Pro",
                            Price = 14990m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 2,
                            Description = "The Dell Alienware Aurora R10 is a high-performance gaming desktop with powerful hardware and customizable lighting.",
                            Discount = 20m,
                            Model = "Alienware Aurora R10",
                            Name = "Dell Alienware Aurora R10",
                            Price = 28000m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 3,
                            Description = "The HP Omen 15 is a gaming laptop with a sleek design, high-refresh-rate display, and powerful performance for gaming enthusiasts.",
                            Discount = 15m,
                            Model = "Omen 15",
                            Name = "HP Omen 15",
                            Price = 17999m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 1,
                            Description = "The Apple MacBook Air is a lightweight and portable laptop with a stunning Retina display and all-day battery life.",
                            Discount = 10m,
                            Model = "MacBook Air",
                            Name = "Apple MacBook Air",
                            Price = 12990m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 9,
                            Description = "The Razer Blade 15 is a premium gaming laptop with a sleek design, high-refresh-rate display, and powerful performance.",
                            Discount = 15m,
                            Model = "Blade 15",
                            Name = "Razer Blade 15",
                            Price = 23990m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 4,
                            Description = "The Lenovo ThinkPad X1 Carbon is a premium business laptop with a durable build, long battery life, and top-notch performance.",
                            Discount = 60m,
                            Model = "ThinkPad X1 Carbon",
                            Name = "Lenovo ThinkPad X1 Carbon",
                            Price = 18990m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 5,
                            Description = "The ASUS ROG Zephyrus G14 is a powerful gaming laptop with an ultra-portable design and impressive performance.",
                            Discount = 0m,
                            Model = "ROG Zephyrus G14",
                            Name = "ASUS ROG Zephyrus G14",
                            Price = 17000m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 8,
                            Description = "The MSI GS66 Stealth is a high-performance gaming laptop with a sleek design and powerful components.",
                            Discount = 19m,
                            Model = "GS66 Stealth",
                            Name = "MSI GS66 Stealth",
                            Price = 23999m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 8,
                            Description = "The MSI Prestige 14 is a stylish and powerful laptop designed for creative professionals.",
                            Discount = 17m,
                            Model = "Prestige 14",
                            Name = "MSI Prestige 14",
                            Price = 15990m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 7,
                            Description = "The Microsoft Surface Laptop 4 is a sleek and versatile laptop with a premium design and excellent performance.",
                            Discount = 14m,
                            Model = "Surface Laptop 4",
                            Name = "Microsoft Surface Laptop 4",
                            Price = 23000m,
                            ProductImageURL = ""
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 7,
                            Description = "The Microsoft Surface Pro 7 is a powerful 2-in-1 tablet-laptop hybrid with a detachable keyboard and versatile functionality.",
                            Discount = 0m,
                            Model = "Surface Pro 7",
                            Name = "Microsoft Surface Pro 7",
                            Price = 20000m,
                            ProductImageURL = ""
                        });
                });

            modelBuilder.Entity("E_commerceAPI.DAL.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("E_commerceAPI.DAL.Product", b =>
                {
                    b.HasOne("E_commerceAPI.DAL.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("E_commerceAPI.DAL.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("E_commerceAPI.DAL.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_commerceAPI.DAL.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("E_commerceAPI.DAL.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("E_commerceAPI.DAL.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
